name: CI/CD pipeline for a Java application using GitHub actions
on:
  push:
    branches:
      - master

jobs:
  build-java-app:
    name: Build and Deploy Java app
    runs-on: ubuntu-latest #OS for the runner
    steps:
      - uses: actions/checkout@v3

      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-


      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'


      #      - name: Cache Maven packages  # Cache dependencies to speed up builds
      #        uses: actions/cache@v3
      #        with:
      #          path: ~/.m2/repository
      #          key: ${{ runner.os }}-maven-${{ hashFiles('pom.xml') }}
      #          restore-keys: |
      #            ${{ runner.os }}-maven-
      - name: Check for Maven
          run: mvn -v

      - name: Build app
        run: |
          mvn clean
          mvn -B package --file pom.xml

      - name: Login to Docker Hub
        uses: docker/login-action@v3  # Use the latest stable version (check for updates)
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}


      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .  # Assuming Dockerfile is in the root directory
          dockerfile: Dockerfile
          push: true
          tags: user/app:latest