name: CI/CD Pipeline with github actions
on:
  push:
    branches:
      - main

jobs:
  build-java-app:
    name: Build and Deploy Java app
    runs-on: ubuntu-latest #OS for the runner
    steps:
      - name: Checkout code  # Update to recommended version
        uses: actions/checkout@v3 # Consider updating to latest stable version (e.g., v3.1)

      - name: Set Node.js 20.x
          uses: actions/setup-node@v20
          with:
            node-version: 20.x

      - name: Setup JDK 17  # Update to recommended version
        uses: actions/setup-java@v4  # Update to v3 (or latest stable version)
        with:
          distribution: 'corretto'  # Replace if using option 1 from point 1
          java-version: 17

      #      - name: Cache Maven packages  # Cache dependencies to speed up builds
      #        uses: actions/cache@v3
      #        with:
      #          path: ~/.m2/repository
      #          key: ${{ runner.os }}-maven-${{ hashFiles('pom.xml') }}
      #          restore-keys: |
      #            ${{ runner.os }}-maven-


      - name: Build app
        run: |
          mvn clean
          mvn -B package --file pom.xml  # Typo fixed (pom.xml instead of pop.xml)



      - name: Sing in to docker-hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_HUB_USERNAME}}
          passwords: ${{secrets.DOCKER_HUB_TOKEN}}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .  # Assuming Dockerfile is in the root directory
          dockerfile: Dockerfile
          push: true
          tags: user/app:latest