name: CI/CD pipeline for a Java application using GitHub actions
on:
  push:
    branches:
      - master

jobs:
  build-java-app:
    name: Build and Deploy Java app
    runs-on: ubuntu-latest #OS for the runner
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
          with:
            node-version: 20
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'


      - name: Cache Maven packages  # Cache dependencies to speed up builds
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build app
        run: |
          mvn clean
          mvn -B package --file pom.xml
      - name: Sing in to docker-hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_HUB_USERNAME}}
          passwords: ${{secrets.DOCKER_HUB_TOKEN}}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .  # Assuming Dockerfile is in the root directory
          dockerfile: Dockerfile
          push: true
          tags: user/app:latest